bills/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


from .views import BillList, BillDetail, BillUpdate
urlpatterns = [

    url(r'^$', BillList.as_view( template_name ='bills/bill_list.html') , name="bill_list" ),
    url(r'^(?P<pk>\d+)/$', BillDetail.as_view( template_name ='bills/bill_detail.html'), name="bill_detail"  ),
    # url(r'^create/$', CustomerCreate.as_view( template_name = 'customers/customer_form.html' ), name="customer_create" ),
    url(r'^(?P<pk>\d+)/edit/$', BillUpdate.as_view( template_name = 'bills/bill_form.html' ), name="bill_edit" ),

    url(r'^(?P<id>\d+)/deleteitem/$', views.billitem_delete ),
    url(r'^checkout/(?P<id>\d+)/$', views.bill_create ),
    url(r'^bill_genegerate/$', views.generate_bill, name="genegerate_bills" ),
    url(r'^print_bills/$', views.print_bills, name="print_bills" ),

    url(r'^(?P<id>\d+)/gen_pdfv2/$', views.gen_pdfv2 , name="gen_pdfv2" ),


]

customers/urls.py
from django.conf.urls import url
from django.contrib import admin


from .views import CustomerList, CustomerDetail,CustomerCreate,CustomerUpdate
urlpatterns = [

    url(r'^$', CustomerList.as_view( template_name ='customers/customer_list.html') , name="customer_list" ),
    url(r'^(?P<pk>\d+)/$', CustomerDetail.as_view( template_name ='customers/customer_detail.html'), name="customer_detail"  ),
    url(r'^create/$', CustomerCreate.as_view( template_name = 'customers/customer_form.html' ), name="customer_create" ),
    url(r'^(?P<pk>\d+)/edit/$', CustomerUpdate.as_view( template_name = 'customers/customer_form.html' ), name="customer_edit" ),


]

workflow/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin

from .views import IndexList


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexList.as_view(),name="index"),
    url(r'^customers/', include( 'customers.urls', namespace="customers")),
    url(r'^dailywork/', include( 'dailywork.urls', namespace="dailywork")),
    url(r'^bills/', include( 'bills.urls', namespace="bills")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.

#客戶
class Customer(models.Model):

    title = models.CharField(max_length=36, null=False, blank=False, verbose_name='客戶名稱')
    unikey = models.CharField(  max_length=12,null=True, blank=True, verbose_name='統一編號' )
    address = models.CharField( max_length=100, null=True, blank=True, verbose_name='地址')

    phone = models.CharField(max_length=20, null=True, blank=True, verbose_name='電話')
    faxno = models.CharField(max_length=20, null=True, blank=True, verbose_name='傳真')

    invalid = models.BooleanField(default=False, verbose_name='停用')

    create_at = models.DateTimeField(auto_now_add=True, auto_now =False)
    modify = models.DateTimeField(auto_now_add=False, auto_now =True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse( "customers:customer_detail", kwargs={"pk": self.pk} )

dailywork/models.py
from django.db import models

from django.utils import timezone
from django.core.urlresolvers import reverse

from customers.models import Customer

# Create your models here.
class Uom(models.Model):
	descriotion =  models.CharField(  max_length=20, null=False, blank=False )

	def __str__(self):
		return self.descriotion


class DailylogQueryset(models.query.QuerySet):

	# 未請款的項目
	def norequest(self):
		return self.filter(payrequest=False , is_freecharge=False , invalid= False  )



class DailylogManager(models.Manager):

	def get_queryset(self):
		return DailylogQueryset(self.model, using=self.db)

	# 未請款的項目
	def norequest(self, *args, **kwargs):
		return self.query_set().norequest()



class Dailylog(models.Model):

	work_date = models.DateField( default=timezone.now )
	customer = models.ForeignKey(Customer)
	start_at = models.CharField(  max_length=20, null=False, blank=False )
	end_with = models.CharField(  max_length=20, null=False, blank=False )
	opreateDesc = models.CharField(max_length=20, blank=False, null=False)
	quantity = models.DecimalField( max_digits=10, decimal_places=0)
	uom = models.ForeignKey(Uom)
	uniprice = models.DecimalField( max_digits=10, decimal_places=0)
	notes = models.TextField(blank=True, null=True)

	payrequest = models.BooleanField(default=False, verbose_name='已請款')    # 是否已請款
	is_freecharge = models.BooleanField(default=False, verbose_name='免費項目')    # 是否爲免費項目, 如果為免費項目則在未請款清單是不會顯示的
	bill_number = models.CharField(  max_length=20, null=True, blank=True )
	invalid = models.BooleanField(default=False, verbose_name='項目作廢')
	create_at = models.DateTimeField( auto_now_add=True, auto_now=False)
	modify = models.DateTimeField( auto_now_add=False, auto_now=True)

	objects = DailylogManager()

	def __str__(self):
		return self.opreateDesc

	def get_absolute_url(self):
		return reverse( "dailywork:dailywork_edit", kwargs={"pk": self.pk} )

	def get_amount(self):
		return self.quantity * self.uniprice

customers/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Customer

class CustomerForm(forms.ModelForm):
    title = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'    } ),label='客戶名稱' )
    unikey = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'  } ),label='統一編號',required=False )
    address = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'} ),label='發票地址',required=False )
    phone = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'    } ),label='聯絡電話' ,required=False)
    faxno = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'   } ),label='傳真號碼',required=False )

    class Meta:
        model = Customer
        exclude = ('create_at','modify','invalid' )


class CustomerEditForm(forms.ModelForm):
    title = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control' } ),label='客戶名稱' )
    unikey = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control' , } ),label='統一編號',required=False )
    address = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control' } ) ,label='發票地址',required=False)
    phone = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'   } ),label='聯絡電話' ,required=False )
    faxno = forms.CharField( widget= forms.TextInput( attrs={'class':'form-control'  } ),label='傳真號碼',required=False )


    class Meta:
        model = Customer
        exclude = ('create_at','modify' )

customers/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic.detail import  DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Q

# Create your views here.
from .models import Customer
from .forms import CustomerForm,CustomerEditForm


class CustomerDetail(DetailView):
    model = Customer



class CustomerList(ListView):
    model = Customer
    paginate_by = 15

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query_list = Customer.objects.filter(
                Q(title__icontains=query)
            ).distinct()
            return query_list

        return Customer.objects.all()



class CustomerCreate(CreateView):
    subject = "Create New Customer"
    model = Customer
    form_class = CustomerForm
    #fields = ['part_number', 'description', 'specification', 'image',  'category', 'cycle_status']
    success_url = reverse_lazy('customers:customer_list')



class CustomerUpdate(UpdateView):
    model = Customer
    form_class = CustomerEditForm
    #fields = ['title', 'unikey', 'address', 'phone', 'faxno', 'invalid']

    success_url = reverse_lazy('customers:customer_list')


class CustomerDelete(DeleteView):
    model = Customer
    #success_url = '/products'
    success_url = reverse_lazy('customers:customer_list')

templates/customers/customer_detail.html
{% extends "base.html" %}



{% block content %}
<script type="text/javascript">
function CreateOnSubmit( str ){

  var items = document.getElementsByName("dailylogs");
  var schecked = 0;
  for( x=0; x < items.length; x++ ){
    if(items[x].checked== true){
        schecked += 1;
      }
  }
  // window.alert( schecked );

  if(schecked==0){
      window.alert("沒有選擇要請款的項目喔");
      return false;
  }else{
    var iChoose = confirm("勾選的項目是否確定為要請款的資料？");

    if(!iChoose){
      return false;
    }else{

      document.getElementById("createform").action = "/bills/checkout/"+{{ customer.id }}+"/";
      createform.submit();

    }
  }
  return true;
}
</script>



<strong>客戶編號：</strong>{{ object.id }}<br>
<strong>客戶名稱：</strong>{{ object.title }}<br>
<strong>統一編號：</strong>{{ object.unikey }}<br>
<strong>電話：</strong>{{ object.phone }}<br>
<strong>傳真：</strong>{{ object.faxno }}<br>
<strong>地址：</strong>{{ object.address }}<br>
<a href="{{ instance.get_absolute_url }}edit" class="btn btn-warning" role="button">編輯客戶主檔</a>
<hr>

<!--
<form   action="" method="POST"> -->

    <div align="center"  >
      <h2><strong>未請款明細</strong></h2>
    </div>
<form id="createform" action="" method="POST" onsubmit="return CreateOnSubmit({{ bill.id }})" >{% csrf_token %}
    <div >
      <input type="text" id="customer_id" name="customer" value="{{ object.id }}" hidden="True"/>
      <button type="submit"  class="btn btn-success form-control">請款</button>
    </div>

  <table class="table table-striped" >
    <tr>
      <th width="5%"><input type="checkbox" value="核取方塊" id="CheckAll" />項次</th>
      <th width="15%">工作日期</th>
      <th width="15%">地點起迄</th>
      <th width="20%">工作描述</th>
      <th width="10%">數量</th>
      <th width="10%">單價</th>
      <th width="10%">金額</th>
      <th >備註事項</th>
    </tr>
  {% for dailylog in object.dailylog_set.all.norequest %}
    <tr>
        <td><input type="checkbox" class='cb' name="dailylogs"  value="{{ dailylog.id }}" />{{ forloop.counter }}</td>
        <td>{{ dailylog.work_date }}</td>
        <td>{{ dailylog.start_at }}-{{ dailylog.end_with }}</td>
        <td>{{ dailylog.opreateDesc }}</td>
        <td>{{ dailylog.quantity }}{{ dailylog.uom }}</td>
        <td>{{ dailylog.uniprice }}</td>
        <td>{{ dailylog.get_amount }}</td>
        <td>{{ dailylog.notes }}</td>
    </tr>
  {% endfor %}


  </table>
</form>
<script>
  $( document ).ready(function() {
    $("#CheckAll").change(function(){
      var check = $(this).is(":checked");
      $(".cb").prop("checked", check);
    });
  });
</script>
{% endblock content %}

templates/customers/customer_form.html
{% extends "base.html" %}



{% block content %}

  <div class="col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3" >

<form action='' method="POST"  enctype="multipart/form-data" >{% csrf_token %}
  {% for field in form %}
  <div class="fieldWrapper">
          {{ field.errors }}
          <p>{{ field.label_tag }}</p><p> {{ field }}</p>
          {% if field.help_text %}
          <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
      </div>
      {% endfor %}
<input type="submit" class="btn btn-primary form-control" value="送出"/>
</form>
</div>



{% endblock content %}

templates/customers/customer_list.html
{% extends "base.html" %}

{% block content %}


{% include "searchbar.html" %}

<div>
<table class="table table-striped" >
  <tr>
    <th width="5%">項次</th>
    <th width="5%">Mark</th>
    <th width="20%">客戶名稱</th>
    <th width="10%">統一編號</th>
    <th width="10%">聯絡電話</th>
    <th width="10%">傳真</th>
    <th >地址</th>

  </tr>
{% for record in object_list %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>

      {% if record.invalid %}
      <strong class="label label-danger">停用</strong>
      {% endif %}</td>
    <td><a href='{{ record.get_absolute_url }}'>{{ record.title }}</a>
      {% if record.dailylog_set.all.norequest.count  %}
      <span class="badge bg-blue">
      {{ record.dailylog_set.all.norequest.count }}
      </span>
      {% endif %}
    </td>
    <td>{{ record.unikey }}</td>
    <td>{{ record.phone }}</td>
    <td>{{ record.faxno }}</td>
    <td>{{ record.address }} </td>
  </tr>
{% endfor %}
</table>
</div>

{% include "pageine.html" %}

{% endblock content %}